# Hexo Configuration
# Docs: https://hexo.io/docs/configuration.html
# Source: https://github.com/hexojs/hexo/

# Site
# title: Molier
# subtitle: Tomorrow is another day
# description: iOS 开发 移动App 博客 杂谈 随笔 相册
# author: Molier
# language: zh-Hans
# timezone:
# avatar: https://image-1256056152.cos.ap-nanjing.myqcloud.com/shiba.gif

# # URL
# ## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: https://oliverqueen.cn
# root: /
# permalink: :year/:month/:day/:title/
# permalink_defaults:

# # 搜索相关
# # search:
# # path: search.xml
# # field: post
# # format: html
# # limit: 10000

# # Directory
# source_dir: source
# public_dir: public
# tag_dir: tags
# archive_dir: archives
# category_dir: categories
# code_dir: downloads/code
# i18n_dir: :lang
# skip_render:

# # Writing
# new_post_name: :year-:month-:day-:title.md # File name of new posts
# default_layout: post
# titlecase: false # Transform title into titlecase
# external_link: true # Open external links in new tab
# filename_case: 0
# render_drafts: false
# post_asset_folder: false
# relative_link: false
# future: true
# highlight:
#   enable: true
#   line_number: false
#   auto_detect: true
#   tab_replace:
# # 停用默认代码高亮功能，否则代码块的 mac 样式不能正常显示。
# # highlight:
# #   enable: false
# prismjs:
#   enable: false

# # Home page setting
# # path: Root path for your blogs index page. (default = '')
# # per_page: Posts displayed per page. (0 = disable pagination)
# # order_by: Posts order. (Order by date descending by default)
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date

# # Category & Tag
# default_category: uncategorized
# category_map:
# tag_map:

# # Date / Time format
# ## Hexo uses Moment.js to parse and display date
# ## You can customize the date format as defined in
# ## http://momentjs.com/docs/#/displaying/format/
# date_format: YYYY-MM-DD
# time_format: HH:mm:ss

# # Pagination
# ## Set per_page to 0 to disable pagination
# per_page: 10
# pagination_dir: page

# # Extensions
# ## Plugins: https://hexo.io/plugins/
# ## Themes: https://hexo.io/themes/
# ## shoka:  https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/
# theme: shoka


# # 搜索相关
# plugins:
#   - hexo-algoliasearch
# algolia:
#   appId: "Z7A3XW4R2I"
#   apiKey: "12db1ad54372045549ef465881c17e743"
#   adminApiKey: "40321c7c207e7f73b63a19aa24c4761b"
#   chunkSize: 5000
#   indexName: "my-hexo-blog"
#   fields:
#     - content:strip:truncate,0,500
#     - excerpt:strip
#     - gallery
#     - permalink
#     - photos
#     - slug
#     - tags
#     - title

# # 字数统计相关
#   symbols_count_time:
#     symbols: true
#     time: true
#     total_symbols: true
#     total_time: true
#     exclude_codeblock: false
#     awl: 4
#     wpm: 275
#     suffix: "mins."

#   keywords: 关键词,关键词12

# #  feed相关
#   feed:
#     limit: 20
#     order_by: "-date"
#     tag_dir: "tag"
#     category_dir: "category"
#     rss:
#         enable: true
#         template: "themes/theme/layout/_alternate/rss.ejs"
#         output: "rss.xml"
#     atom:
#         enable: true
#         template: "themes/theme/layout/_alternate/atom.ejs"
#         output: "atom.xml"
#     jsonFeed:
#         enable: true
#         template: "themes/theme/layout/_alternate/json.ejs"
#         output: "feed.json"

# # hexo sitemap网站地图
# sitemap:
#   path: sitemap.xml
# baidusitemap:
#   path: baidusitemap.xml


# # markdown编辑器一些设置
# markdown:
#   render:
#     html: false
#     xhtmlOut: true
#     breaks: true
#     linkify: true
#     typographer: 
#     quotes: '“”‘’'
#   plugins:
#     - plugin:
#         name: markdown-it-toc-and-anchor
#         enable: true
#         options:
#           tocClassName: 'toc'
#           anchorClassName: 'anchor'
#     - plugin:
#         name: markdown-it-multimd-table
#         enable: true
#         options:
#           multiline: true
#           rowspan: true
#           headerless: true
#     - plugin:
#         name: ./markdown-it-furigana
#         enable: true
#         options:
#           fallbackParens: "()"
#     - plugin:
#         name: ./markdown-it-spoiler
#         enable: true
#         options:
#           title: "你知道得太多了"
 
# # markdown编辑器一些设置 for minify
# # 加入 minify 配置，压缩 css/js/html
# minify:
#   html:
#     enable: true
#     exclude:
#       - '**/json.ejs'
#       - '**/atom.ejs'
#       - '**/rss.ejs'
#   css:
#     enable: true
#     exclude:
#       - '**/*.min.css'
#   js:
#     enable: true
#     mangle:
#       toplevel: true
#     output:
#     compress:
#     exclude:
#       - '**/*.min.js'

# # 给生成的 css 文件们添加浏览器前缀
# autoprefixer:
#   exclude:
#     - '*.min.css'
#   browsers:
#     - 'last 2 versions'

# Deployment:
# # Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: git
#   repo: git@github.com:MolierQueen/molierqueen.github.io.git
#   branch: master



  ########################################

  # Hexo Configuration
# Docs: http://hexo.io/docs/configuration.html
# Source: https://github.com/hexojs/hexo/

# Site
title: Molier
subtitle: Tomorrow is another day
description: iOS 开发 移动App 博客 杂谈 随笔 相册
keywords: 关键词1,关键词2 # edit for Theme.shoka
author: Molier
language: zh-CN # 这里只可以选 zh-CN、zh-HK、zh-TW、ja、en 这几个格式
timezone: 'Asia/Shanghai'
avatar: https://image-1256056152.cos.ap-nanjing.myqcloud.com/shiba.gif

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://oliverqueen.cn
root: /
permalink: :title/ # edit for Theme.shoka
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true # edit for Theme.shoka
  line_number: true
  auto_detect: true
  tab_replace: ''
prismjs:
  enable: false # edit for Theme.shoka

# Category & Tag
default_category: uncategorized
category_map: # edit for Theme.shoka
  计算机科学: computer-science
  Java: java
  二进制杂谈: note
  零基础学Java语言-浙江大学-翁恺: course-1
  Theme Shoka Documentation: theme-shoka-doc
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: shoka # edit for Theme.shoka

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:MolierQueen/molierqueen.github.io.git
  branch: master


# edit for Theme.shoka
autoprefixer:
  exclude:
    - '*.min.css'

markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer:
    quotes: '“”‘’'
  plugins: # markdown-it插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的class名称，shoka主题必须设置成这样
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"

minify:
  html:
    enable: true
    stamp: false
    exclude:
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    stamp: false
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    stamp: false
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'

# 搜索相关
plugins:
  - hexo-algoliasearch
algolia:
  appId: "Z7A3XW4R2I"
  apiKey: "12db1ad54372045549ef465881c17e743"
  adminApiKey: "40321c7c207e7f73b63a19aa24c4761b"
  chunkSize: 5000
  indexName: "my-hexo-blog"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title

#  feed相关
  feed:
    limit: 20
    order_by: "-date"
    tag_dir: "tag"
    category_dir: "category"
    rss:
        enable: true
        template: "themes/theme/layout/_alternate/rss.ejs"
        output: "rss.xml"
    atom:
        enable: true
        template: "themes/theme/layout/_alternate/atom.ejs"
        output: "atom.xml"
    jsonFeed:
        enable: true
        template: "themes/theme/layout/_alternate/json.ejs"
        output: "feed.json"

